/**
 * €N€RGY - Database Seed Script
 *
 * Popola il database con i dati reali di Andrea Vaturi:
 * - Soggetti (persone e aziende)
 * - Contenitori (tutti i conti, carte, trading, crypto, etc.)
 * - Tag di base (categorie, ambiti, finalita')
 * - Controparti frequenti
 *
 * Eseguire con: npm run db:seed
 */

import 'dotenv/config'
import { neon } from '@neondatabase/serverless'
import { drizzle } from 'drizzle-orm/neon-http'
import { v4 as uuid } from 'uuid'
import * as schema from './schema'

async function seed() {
  const databaseUrl = process.env.DATABASE_URL
  if (!databaseUrl) {
    console.error('DATABASE_URL non configurato. Crea un file .env con la connection string di Neon.')
    process.exit(1)
  }

  const sql = neon(databaseUrl)
  const db = drizzle(sql, { schema })

  console.log('Seeding €N€RGY database...\n')

  // ============================================================
  // SOGGETTI
  // ============================================================
  console.log('1. Creazione soggetti...')

  // Persone
  const andreaId = uuid()
  const mirkoId = uuid()
  const moglieId = uuid()
  const massimoId = uuid()

  // Aziende
  const kairosId = uuid()
  const scaccoMattoId = uuid()
  const shuffleId = uuid()
  const aceOfDiamondsId = uuid()
  const unfairAdvantageId = uuid()
  const tlfAdvisoryId = uuid()
  const ltdUkId = uuid()

  const subjectsData = [
    // Persone fisiche
    {
      id: andreaId,
      type: 'person' as const,
      name: 'Andrea Vaturi',
      taxId: null,
      country: 'IT',
      role: 'owner' as const,
      parentSubjectId: null,
      notes: 'Titolare. Libero professionista (P.IVA) + imprenditore.',
      isActive: true,
    },
    {
      id: moglieId,
      type: 'person' as const,
      name: 'Moglie AV',
      country: 'IT',
      role: 'family' as const,
      parentSubjectId: andreaId,
      notes: 'Ha una Amex collegata al conto di Andrea.',
      isActive: true,
    },
    {
      id: massimoId,
      type: 'person' as const,
      name: 'Massimo Vaturi',
      country: 'IT',
      role: 'family' as const,
      parentSubjectId: andreaId,
      notes: 'Figlio. Ha una prepagata.',
      isActive: true,
    },
    {
      id: mirkoId,
      type: 'person' as const,
      name: 'Mirko Castignani',
      country: 'IT',
      role: 'partner' as const,
      parentSubjectId: null,
      notes: 'Socio al 50% in Vantaggio Sleale / Opzionetika. Titolare di Scacco Matto SRLS.',
      isActive: true,
    },
    // Aziende
    {
      id: kairosId,
      type: 'company' as const,
      name: 'Kairos SRLS',
      legalForm: 'SRLS',
      country: 'IT',
      role: 'owner' as const,
      parentSubjectId: andreaId,
      notes: 'SRL di Andrea al 100%. Interfaccia principale per il business VS/Opzionetika.',
      isActive: true,
    },
    {
      id: scaccoMattoId,
      type: 'company' as const,
      name: 'Scacco Matto SRLS',
      legalForm: 'SRLS',
      country: 'IT',
      role: 'partner' as const,
      parentSubjectId: mirkoId,
      notes: 'SRL di Mirko Castignani. Business 50/50 con Kairos per VS/Opzionetika.',
      isActive: true,
    },
    {
      id: shuffleId,
      type: 'company' as const,
      name: 'Shuffle SSRL',
      legalForm: 'SSRL',
      country: 'IT',
      role: 'other' as const,
      parentSubjectId: andreaId,
      notes: 'Gestisce Ghiaccio Spettacolo. Andrea socio al 33%.',
      isActive: true,
    },
    {
      id: aceOfDiamondsId,
      type: 'company' as const,
      name: 'Ace of Diamonds SRL',
      legalForm: 'SRL',
      country: 'RO',
      role: 'owner' as const,
      parentSubjectId: andreaId,
      notes: 'Azienda rumena. Probabilmente in fase di chiusura.',
      isActive: true,
    },
    {
      id: unfairAdvantageId,
      type: 'company' as const,
      name: 'Unfair Advantage SRL',
      legalForm: 'SRL',
      country: 'RO',
      role: 'owner' as const,
      parentSubjectId: andreaId,
      notes: 'Azienda rumena. Probabilmente in fase di chiusura.',
      isActive: true,
    },
    {
      id: tlfAdvisoryId,
      type: 'company' as const,
      name: 'TLF Advisory SRLS',
      legalForm: 'SRLS',
      country: 'IT',
      role: 'other' as const,
      parentSubjectId: null,
      notes: 'Ha un conto Revolut aziendale.',
      isActive: true,
    },
    {
      id: ltdUkId,
      type: 'company' as const,
      name: 'LTD UK (VS/Opzionetika)',
      legalForm: 'LTD',
      country: 'GB',
      role: 'partner' as const,
      parentSubjectId: null,
      notes: 'LTD inglese condivisa con Mirko Castignani.',
      isActive: true,
    },
  ]

  await db.insert(schema.subjects).values(subjectsData)
  console.log(`   ${subjectsData.length} soggetti creati`)

  // ============================================================
  // CONTENITORI - Conti miei (personali di Andrea)
  // ============================================================
  console.log('2. Creazione contenitori...')

  let sortOrder = 0
  const containersData = [
    // --- CONTI CORRENTI ---
    {
      id: uuid(),
      subjectId: andreaId,
      name: 'ISP 2767',
      type: 'bank_account' as const,
      provider: 'Intesa Sanpaolo',
      currency: 'EUR',
      isMultiCurrency: false,
      initialBalance: '0',
      icon: 'landmark',
      color: '#0066CC',
      sortOrder: sortOrder++,
      isActive: true,
      notes: 'Conto corrente principale personale.',
    },
    {
      id: uuid(),
      subjectId: andreaId,
      name: 'Revolut Personal',
      type: 'bank_account' as const,
      provider: 'Revolut',
      currency: 'EUR',
      isMultiCurrency: true,
      initialBalance: '100',
      icon: 'smartphone',
      color: '#0075EB',
      sortOrder: sortOrder++,
      isActive: true,
      notes: 'Conto Revolut personale. Multi-valuta + risparmio.',
    },
    // --- CONTANTI ---
    {
      id: uuid(),
      subjectId: andreaId,
      name: 'Contanti',
      type: 'cash' as const,
      provider: null,
      currency: 'EUR',
      isMultiCurrency: false,
      initialBalance: '0',
      icon: 'banknote',
      color: '#22C55E',
      sortOrder: sortOrder++,
      isActive: true,
      notes: 'Cash fisico.',
    },
    // --- SERVIZI DI PAGAMENTO ---
    {
      id: uuid(),
      subjectId: andreaId,
      name: 'PayPal',
      type: 'payment_service' as const,
      provider: 'PayPal',
      currency: 'EUR',
      isMultiCurrency: true,
      initialBalance: '0',
      icon: 'smartphone',
      color: '#003087',
      sortOrder: sortOrder++,
      isActive: true,
      notes: 'PayPal personale. Se saldo insufficiente, prende da Amex o ISP.',
    },
    {
      id: uuid(),
      subjectId: andreaId,
      name: 'Satispay',
      type: 'payment_service' as const,
      provider: 'Satispay',
      currency: 'EUR',
      isMultiCurrency: false,
      initialBalance: '100',
      icon: 'smartphone',
      color: '#EF4444',
      sortOrder: sortOrder++,
      isActive: true,
      notes: 'Ricarica automatica settimanale da ISP.',
    },
    // --- CARTE DI CREDITO ---
    {
      id: uuid(),
      subjectId: andreaId,
      name: 'American Express Oro - AV',
      type: 'credit_card' as const,
      provider: 'American Express',
      currency: 'EUR',
      isMultiCurrency: false,
      initialBalance: '0',
      billingDay: 10,
      icon: 'credit-card',
      color: '#C5A44E',
      sortOrder: sortOrder++,
      isActive: true,
      notes: 'Amex Oro personale di Andrea. Addebito su ISP.',
    },
    {
      id: uuid(),
      subjectId: andreaId,
      name: 'American Express Oro - VS',
      type: 'credit_card' as const,
      provider: 'American Express',
      currency: 'EUR',
      isMultiCurrency: false,
      initialBalance: '0',
      billingDay: 10,
      icon: 'credit-card',
      color: '#C5A44E',
      sortOrder: sortOrder++,
      isActive: true,
      notes: 'Amex Oro per Vantaggio Sleale. Addebito su ISP.',
    },
    {
      id: uuid(),
      subjectId: andreaId,
      name: 'American Express Revolving',
      type: 'credit_card' as const,
      provider: 'American Express',
      currency: 'EUR',
      isMultiCurrency: false,
      initialBalance: '0',
      icon: 'credit-card',
      color: '#8B7355',
      sortOrder: sortOrder++,
      isActive: true,
      notes: 'Amex revolving.',
    },
    {
      id: uuid(),
      subjectId: moglieId,
      name: 'American Express Moglie',
      type: 'credit_card' as const,
      provider: 'American Express',
      currency: 'EUR',
      isMultiCurrency: false,
      initialBalance: '0',
      billingDay: 10,
      icon: 'credit-card',
      color: '#C5A44E',
      sortOrder: sortOrder++,
      isActive: true,
      notes: 'Amex intestata alla moglie, collegata al conto di Andrea.',
    },
    // --- RISPARMIO ---
    {
      id: uuid(),
      subjectId: andreaId,
      name: 'Fondo ca$$a',
      type: 'savings' as const,
      provider: null,
      currency: 'EUR',
      isMultiCurrency: false,
      initialBalance: '1300',
      icon: 'piggy-bank',
      color: '#F59E0B',
      sortOrder: sortOrder++,
      isActive: true,
      notes: 'Fondo cassa di emergenza.',
    },
    {
      id: uuid(),
      subjectId: andreaId,
      name: 'New York Piggy',
      type: 'savings' as const,
      provider: null,
      currency: 'EUR',
      isMultiCurrency: false,
      initialBalance: '0',
      icon: 'piggy-bank',
      color: '#EC4899',
      sortOrder: sortOrder++,
      isActive: true,
      notes: 'Salvadanaio/accantonamento.',
    },
    // --- TRADING ---
    {
      id: uuid(),
      subjectId: andreaId,
      name: 'Interactive Brokers AV',
      type: 'trading' as const,
      provider: 'Interactive Brokers',
      currency: 'EUR',
      isMultiCurrency: true,
      initialBalance: '100',
      icon: 'trending-up',
      color: '#D62B1F',
      sortOrder: sortOrder++,
      isActive: true,
      notes: 'Conto trading personale di Andrea su IB.',
    },
    {
      id: uuid(),
      subjectId: andreaId,
      name: 'Trade Republic',
      type: 'trading' as const,
      provider: 'Trade Republic',
      currency: 'EUR',
      isMultiCurrency: false,
      initialBalance: '11000',
      icon: 'trending-up',
      color: '#1A1A2E',
      sortOrder: sortOrder++,
      isActive: true,
      notes: 'Investing. Saldo €11.000.',
    },
    {
      id: uuid(),
      subjectId: andreaId,
      name: 'iBroker.it',
      type: 'trading' as const,
      provider: 'iBroker',
      currency: 'EUR',
      isMultiCurrency: false,
      initialBalance: '270.60',
      icon: 'trending-up',
      color: '#FF6600',
      sortOrder: sortOrder++,
      isActive: true,
    },
    {
      id: uuid(),
      subjectId: andreaId,
      name: 'Webank Trading',
      type: 'trading' as const,
      provider: 'Webank',
      currency: 'EUR',
      isMultiCurrency: false,
      initialBalance: '1627.73',
      icon: 'trending-up',
      color: '#006837',
      sortOrder: sortOrder++,
      isActive: true,
    },
    {
      id: uuid(),
      subjectId: andreaId,
      name: 'Daniotti',
      type: 'trading' as const,
      provider: 'Daniotti',
      currency: 'EUR',
      isMultiCurrency: false,
      initialBalance: '3000',
      icon: 'trending-up',
      color: '#D4A017',
      sortOrder: sortOrder++,
      isActive: true,
    },
    {
      id: uuid(),
      subjectId: andreaId,
      name: 'IG',
      type: 'trading' as const,
      provider: 'IG',
      currency: 'EUR',
      isMultiCurrency: true,
      initialBalance: '0',
      icon: 'trending-up',
      color: '#DC143C',
      sortOrder: sortOrder++,
      isActive: true,
    },
    {
      id: uuid(),
      subjectId: andreaId,
      name: 'Soisy',
      type: 'trading' as const,
      provider: 'Soisy',
      currency: 'EUR',
      isMultiCurrency: false,
      initialBalance: '59.37',
      icon: 'trending-up',
      color: '#5B21B6',
      sortOrder: sortOrder++,
      isActive: true,
      notes: 'P2P lending / investing.',
    },
    {
      id: uuid(),
      subjectId: andreaId,
      name: 'Degiro',
      type: 'trading' as const,
      provider: 'Degiro',
      currency: 'EUR',
      isMultiCurrency: true,
      initialBalance: '129.39',
      icon: 'trending-up',
      color: '#00A3E0',
      sortOrder: sortOrder++,
      isActive: true,
    },
    {
      id: uuid(),
      subjectId: andreaId,
      name: 'Lenndy',
      type: 'trading' as const,
      provider: 'Lenndy',
      currency: 'EUR',
      isMultiCurrency: false,
      initialBalance: '54.01',
      icon: 'trending-up',
      color: '#4A90D9',
      sortOrder: sortOrder++,
      isActive: true,
      notes: 'P2P lending.',
    },
    // --- CRYPTO ---
    {
      id: uuid(),
      subjectId: andreaId,
      name: 'Binance',
      type: 'crypto' as const,
      provider: 'Binance',
      currency: 'EUR',
      isMultiCurrency: true,
      initialBalance: '10000',
      icon: 'bitcoin',
      color: '#F3BA2F',
      sortOrder: sortOrder++,
      isActive: true,
    },
    {
      id: uuid(),
      subjectId: andreaId,
      name: 'Wirex',
      type: 'crypto' as const,
      provider: 'Wirex',
      currency: 'EUR',
      isMultiCurrency: true,
      initialBalance: '0',
      icon: 'bitcoin',
      color: '#00C3FF',
      sortOrder: sortOrder++,
      isActive: true,
    },
    {
      id: uuid(),
      subjectId: andreaId,
      name: 'Crypto.com',
      type: 'crypto' as const,
      provider: 'Crypto.com',
      currency: 'EUR',
      isMultiCurrency: true,
      initialBalance: '197.47',
      icon: 'bitcoin',
      color: '#103F68',
      sortOrder: sortOrder++,
      isActive: true,
    },
    {
      id: uuid(),
      subjectId: andreaId,
      name: 'Coinbase',
      type: 'crypto' as const,
      provider: 'Coinbase',
      currency: 'EUR',
      isMultiCurrency: true,
      initialBalance: '405.94',
      icon: 'bitcoin',
      color: '#0052FF',
      sortOrder: sortOrder++,
      isActive: true,
    },
    {
      id: uuid(),
      subjectId: andreaId,
      name: 'BlockFi',
      type: 'crypto' as const,
      provider: 'BlockFi',
      currency: 'USD',
      isMultiCurrency: false,
      initialBalance: '7.59',
      icon: 'bitcoin',
      color: '#694ED6',
      sortOrder: sortOrder++,
      isActive: false,
      notes: 'Probabilmente chiuso/bloccato.',
    },
    {
      id: uuid(),
      subjectId: andreaId,
      name: 'Deribit',
      type: 'crypto' as const,
      provider: 'Deribit',
      currency: 'USD',
      isMultiCurrency: true,
      initialBalance: '1300',
      icon: 'bitcoin',
      color: '#57E099',
      sortOrder: sortOrder++,
      isActive: true,
      notes: 'Crypto + Trading opzioni.',
    },
    {
      id: uuid(),
      subjectId: andreaId,
      name: 'Trust Wallet',
      type: 'crypto' as const,
      provider: 'Trust Wallet',
      currency: 'USD',
      isMultiCurrency: true,
      initialBalance: '0',
      icon: 'bitcoin',
      color: '#3375BB',
      sortOrder: sortOrder++,
      isActive: true,
    },
    {
      id: uuid(),
      subjectId: andreaId,
      name: 'Polymarket',
      type: 'crypto' as const,
      provider: 'Polymarket',
      currency: 'USD',
      isMultiCurrency: false,
      initialBalance: '100',
      icon: 'bitcoin',
      color: '#4C6EF5',
      sortOrder: sortOrder++,
      isActive: true,
      notes: 'Prediction market.',
    },
    {
      id: uuid(),
      subjectId: andreaId,
      name: 'Climbermine',
      type: 'crypto' as const,
      provider: 'Climbermine',
      currency: 'USD',
      isMultiCurrency: false,
      initialBalance: '1000',
      icon: 'bitcoin',
      color: '#00BFA5',
      sortOrder: sortOrder++,
      isActive: true,
    },
    {
      id: uuid(),
      subjectId: andreaId,
      name: 'MetaMask',
      type: 'crypto' as const,
      provider: 'MetaMask',
      currency: 'USD',
      isMultiCurrency: true,
      initialBalance: '0',
      icon: 'bitcoin',
      color: '#E2761B',
      sortOrder: sortOrder++,
      isActive: true,
      notes: 'Wallet DeFi.',
    },
    {
      id: uuid(),
      subjectId: andreaId,
      name: 'ByBit',
      type: 'crypto' as const,
      provider: 'ByBit',
      currency: 'USD',
      isMultiCurrency: true,
      initialBalance: '1000',
      icon: 'bitcoin',
      color: '#F7A600',
      sortOrder: sortOrder++,
      isActive: true,
    },

    // --- CONTI AZIENDALI ---
    {
      id: uuid(),
      subjectId: kairosId,
      name: 'Interactive Brokers Kairos',
      type: 'trading' as const,
      provider: 'Interactive Brokers',
      currency: 'EUR',
      isMultiCurrency: true,
      initialBalance: '7700',
      icon: 'trending-up',
      color: '#D62B1F',
      sortOrder: sortOrder++,
      isActive: true,
      notes: 'Conto trading aziendale Kairos.',
    },
    {
      id: uuid(),
      subjectId: kairosId,
      name: 'ISP Kairos',
      type: 'bank_account' as const,
      provider: 'Intesa Sanpaolo',
      currency: 'EUR',
      isMultiCurrency: false,
      initialBalance: '0',
      icon: 'landmark',
      color: '#0066CC',
      sortOrder: sortOrder++,
      isActive: true,
      notes: 'Conto corrente aziendale Kairos su Intesa Sanpaolo.',
    },
    {
      id: uuid(),
      subjectId: kairosId,
      name: 'Zurich Bank Kairos',
      type: 'bank_account' as const,
      provider: 'Zurich Bank',
      currency: 'EUR',
      isMultiCurrency: false,
      initialBalance: '0',
      icon: 'landmark',
      color: '#003399',
      sortOrder: sortOrder++,
      isActive: true,
    },
    {
      id: uuid(),
      subjectId: kairosId,
      name: 'Amex Kairos',
      type: 'credit_card' as const,
      provider: 'American Express',
      currency: 'EUR',
      isMultiCurrency: false,
      initialBalance: '0',
      icon: 'credit-card',
      color: '#C5A44E',
      sortOrder: sortOrder++,
      isActive: true,
      notes: 'American Express aziendale Kairos. Esporta Excel/CSV.',
    },
    {
      id: uuid(),
      subjectId: kairosId,
      name: 'PayPal Kairos',
      type: 'payment_service' as const,
      provider: 'PayPal',
      currency: 'EUR',
      isMultiCurrency: true,
      initialBalance: '0',
      icon: 'smartphone',
      color: '#003087',
      sortOrder: sortOrder++,
      isActive: true,
    },
    {
      id: uuid(),
      subjectId: kairosId,
      name: 'Qonto Kairos',
      type: 'bank_account' as const,
      provider: 'Qonto',
      currency: 'EUR',
      isMultiCurrency: false,
      initialBalance: '0',
      icon: 'landmark',
      color: '#7B61FF',
      sortOrder: sortOrder++,
      isActive: true,
    },
    {
      id: uuid(),
      subjectId: kairosId,
      name: 'Stripe Kairos',
      type: 'payment_service' as const,
      provider: 'Stripe',
      currency: 'EUR',
      isMultiCurrency: true,
      initialBalance: '0',
      icon: 'smartphone',
      color: '#635BFF',
      sortOrder: sortOrder++,
      isActive: true,
    },
    {
      id: uuid(),
      subjectId: kairosId,
      name: 'Soldo Kairos',
      type: 'payment_service' as const,
      provider: 'Soldo',
      currency: 'EUR',
      isMultiCurrency: false,
      initialBalance: '0',
      icon: 'smartphone',
      color: '#1A1A1A',
      sortOrder: sortOrder++,
      isActive: true,
    },
    {
      id: uuid(),
      subjectId: kairosId,
      name: 'Saxo Kairos',
      type: 'trading' as const,
      provider: 'Saxo Bank',
      currency: 'EUR',
      isMultiCurrency: true,
      initialBalance: '0',
      icon: 'trending-up',
      color: '#003D6A',
      sortOrder: sortOrder++,
      isActive: true,
    },
    {
      id: uuid(),
      subjectId: kairosId,
      name: 'Wise Kairos',
      type: 'payment_service' as const,
      provider: 'Wise',
      currency: 'EUR',
      isMultiCurrency: true,
      initialBalance: '0',
      icon: 'smartphone',
      color: '#9FE870',
      sortOrder: sortOrder++,
      isActive: true,
    },
    // Conti Romania
    {
      id: uuid(),
      subjectId: aceOfDiamondsId,
      name: 'Banca Transilvania - LEI',
      type: 'bank_account' as const,
      provider: 'Banca Transilvania',
      currency: 'RON',
      isMultiCurrency: false,
      initialBalance: '0',
      icon: 'landmark',
      color: '#FFD700',
      sortOrder: sortOrder++,
      isActive: true,
    },
    {
      id: uuid(),
      subjectId: aceOfDiamondsId,
      name: 'Banca Transilvania - EUR (AoD)',
      type: 'bank_account' as const,
      provider: 'Banca Transilvania',
      currency: 'EUR',
      isMultiCurrency: false,
      initialBalance: '0',
      icon: 'landmark',
      color: '#FFD700',
      sortOrder: sortOrder++,
      isActive: true,
    },
    {
      id: uuid(),
      subjectId: unfairAdvantageId,
      name: 'Banca Transilvania - EUR (UA)',
      type: 'bank_account' as const,
      provider: 'Banca Transilvania',
      currency: 'EUR',
      isMultiCurrency: false,
      initialBalance: '0',
      icon: 'landmark',
      color: '#FFD700',
      sortOrder: sortOrder++,
      isActive: true,
    },
    {
      id: uuid(),
      subjectId: aceOfDiamondsId,
      name: 'Ace of Diamonds - EUR account',
      type: 'bank_account' as const,
      provider: 'Ace of Diamonds',
      currency: 'EUR',
      isMultiCurrency: false,
      initialBalance: '35000',
      icon: 'landmark',
      color: '#DC2626',
      sortOrder: sortOrder++,
      isActive: true,
      notes: 'Conto Gruppo VS. Saldo €35.000.',
    },
    // TLF Advisory
    {
      id: uuid(),
      subjectId: tlfAdvisoryId,
      name: 'Revolut - TLF Advisory',
      type: 'bank_account' as const,
      provider: 'Revolut',
      currency: 'EUR',
      isMultiCurrency: true,
      initialBalance: '0',
      icon: 'smartphone',
      color: '#0075EB',
      sortOrder: sortOrder++,
      isActive: true,
    },

    // --- CONTI GRUPPO VS (condivisi con Mirko) ---
    {
      id: uuid(),
      subjectId: kairosId,
      name: 'tastyworks - tastyClub',
      type: 'trading' as const,
      provider: 'tastytrade',
      currency: 'USD',
      isMultiCurrency: false,
      initialBalance: '5131',
      icon: 'trending-up',
      color: '#CE1141',
      sortOrder: sortOrder++,
      isActive: true,
      notes: 'Gruppo VS. Saldo $5.131.',
    },
    {
      id: uuid(),
      subjectId: kairosId,
      name: 'IB - ProRealTime',
      type: 'trading' as const,
      provider: 'Interactive Brokers',
      currency: 'EUR',
      isMultiCurrency: true,
      initialBalance: '0',
      icon: 'trending-up',
      color: '#D62B1F',
      sortOrder: sortOrder++,
      isActive: true,
      notes: 'Gruppo VS. IB con ProRealTime.',
    },
    {
      id: uuid(),
      subjectId: kairosId,
      name: 'IB - Mastermind',
      type: 'trading' as const,
      provider: 'Interactive Brokers',
      currency: 'EUR',
      isMultiCurrency: true,
      initialBalance: '5000',
      icon: 'trending-up',
      color: '#D62B1F',
      sortOrder: sortOrder++,
      isActive: true,
      notes: 'Gruppo VS Mastermind. Saldo €5.000.',
    },
    {
      id: uuid(),
      subjectId: kairosId,
      name: 'Exante',
      type: 'trading' as const,
      provider: 'Exante',
      currency: 'EUR',
      isMultiCurrency: true,
      initialBalance: '0',
      icon: 'trending-up',
      color: '#1B3A5C',
      sortOrder: sortOrder++,
      isActive: true,
      notes: 'Gruppo VS.',
    },
    {
      id: uuid(),
      subjectId: kairosId,
      name: 'Webank - Portafoglio strategico',
      type: 'trading' as const,
      provider: 'Webank',
      currency: 'EUR',
      isMultiCurrency: false,
      initialBalance: '10000',
      icon: 'trending-up',
      color: '#006837',
      sortOrder: sortOrder++,
      isActive: true,
      notes: 'Gruppo VS. Saldo €10.000.',
    },
    {
      id: uuid(),
      subjectId: kairosId,
      name: 'Schwab',
      type: 'trading' as const,
      provider: 'Charles Schwab',
      currency: 'USD',
      isMultiCurrency: false,
      initialBalance: '0',
      icon: 'trending-up',
      color: '#00A3E0',
      sortOrder: sortOrder++,
      isActive: true,
      notes: 'Gruppo VS.',
    },

    // --- PREPAGATA FIGLIO ---
    {
      id: uuid(),
      subjectId: massimoId,
      name: 'Prepagata Massimo',
      type: 'bank_account' as const,
      provider: null,
      currency: 'EUR',
      isMultiCurrency: false,
      initialBalance: '0',
      icon: 'credit-card',
      color: '#8B5CF6',
      sortOrder: sortOrder++,
      isActive: true,
      notes: 'Prepagata per Massimo.',
    },
  ]

  await db.insert(schema.containers).values(containersData)
  console.log(`   ${containersData.length} contenitori creati`)

  // ============================================================
  // TAG
  // ============================================================
  console.log('3. Creazione tag...')

  const tagsData = [
    // --- SCOPE (ambito) ---
    { id: uuid(), name: 'Personale', type: 'scope' as const, color: '#3B82F6', icon: 'user' },
    { id: uuid(), name: 'Familiare', type: 'scope' as const, color: '#8B5CF6', icon: 'users' },
    { id: uuid(), name: 'Aziendale Kairos', type: 'scope' as const, color: '#F59E0B', icon: 'building' },
    { id: uuid(), name: 'VS / Opzionetika', type: 'scope' as const, color: '#EF4444', icon: 'target' },
    { id: uuid(), name: 'Ghiaccio Spettacolo', type: 'scope' as const, color: '#06B6D4', icon: 'snowflake' },
    { id: uuid(), name: 'Ace of Diamonds', type: 'scope' as const, color: '#DC2626', icon: 'diamond' },

    // --- PURPOSE (finalita') ---
    { id: uuid(), name: 'Da dividere con Mirko', type: 'purpose' as const, color: '#F97316', icon: 'split' },
    { id: uuid(), name: 'Versamento c/capitale', type: 'purpose' as const, color: '#14B8A6', icon: 'arrow-down-to-line' },
    { id: uuid(), name: 'Scaricabile IVA', type: 'purpose' as const, color: '#84CC16', icon: 'receipt' },
    { id: uuid(), name: 'Per conto parenti', type: 'purpose' as const, color: '#D946EF', icon: 'heart-handshake' },
    { id: uuid(), name: 'Accantonamento figli', type: 'purpose' as const, color: '#EC4899', icon: 'baby' },

    // --- CATEGORY (cosa) - Spese personali/familiari ---
    { id: uuid(), name: 'Affitto', type: 'category' as const, color: '#6366F1', icon: 'home' },
    { id: uuid(), name: 'Box', type: 'category' as const, color: '#6366F1', icon: 'car' },
    { id: uuid(), name: 'Bollette', type: 'category' as const, color: '#F59E0B', icon: 'zap' },
    { id: uuid(), name: 'Acqua', type: 'category' as const, color: '#06B6D4', icon: 'droplets' },
    { id: uuid(), name: 'Spesa alimentare', type: 'category' as const, color: '#22C55E', icon: 'shopping-cart' },
    { id: uuid(), name: 'Scuola', type: 'category' as const, color: '#8B5CF6', icon: 'book-open' },
    { id: uuid(), name: 'Milano Ristorazione', type: 'category' as const, color: '#F97316', icon: 'utensils' },
    { id: uuid(), name: 'Baby Sitter', type: 'category' as const, color: '#EC4899', icon: 'baby' },
    { id: uuid(), name: 'Pulizie casa', type: 'category' as const, color: '#14B8A6', icon: 'sparkles' },
    { id: uuid(), name: 'Automobile', type: 'category' as const, color: '#64748B', icon: 'car' },
    { id: uuid(), name: 'Telepass', type: 'category' as const, color: '#3B82F6', icon: 'toll' },
    { id: uuid(), name: 'Assicurazioni', type: 'category' as const, color: '#DC2626', icon: 'shield' },
    { id: uuid(), name: 'Assicurazioni familiari', type: 'category' as const, color: '#DC2626', icon: 'shield-check' },
    { id: uuid(), name: 'Carta di credito', type: 'category' as const, color: '#C5A44E', icon: 'credit-card' },
    { id: uuid(), name: 'Vacanze e viaggi', type: 'category' as const, color: '#0EA5E9', icon: 'plane' },
    { id: uuid(), name: 'Regali', type: 'category' as const, color: '#F43F5E', icon: 'gift' },
    { id: uuid(), name: 'Palestra', type: 'category' as const, color: '#22C55E', icon: 'dumbbell' },
    { id: uuid(), name: 'Capelli', type: 'category' as const, color: '#A855F7', icon: 'scissors' },
    { id: uuid(), name: 'Beneficenza', type: 'category' as const, color: '#F472B6', icon: 'heart' },
    { id: uuid(), name: 'Comunita\' ebraica', type: 'category' as const, color: '#2563EB', icon: 'star' },
    { id: uuid(), name: 'Attivita\' familiari e sportive', type: 'category' as const, color: '#10B981', icon: 'trophy' },

    // --- CATEGORY - Tasse e imposte ---
    { id: uuid(), name: 'TARI', type: 'category' as const, color: '#EF4444', icon: 'file-text' },
    { id: uuid(), name: 'F24 - IVA', type: 'category' as const, color: '#DC2626', icon: 'file-text' },
    { id: uuid(), name: 'F24 - IRPEF', type: 'category' as const, color: '#DC2626', icon: 'file-text' },
    { id: uuid(), name: 'F24 - Cedolini', type: 'category' as const, color: '#DC2626', icon: 'file-text' },
    { id: uuid(), name: 'Multe', type: 'category' as const, color: '#EF4444', icon: 'alert-triangle' },

    // --- CATEGORY - Subscriptions / Strumenti ---
    { id: uuid(), name: 'Netflix', type: 'category' as const, color: '#E50914', icon: 'tv' },
    { id: uuid(), name: 'Disney+', type: 'category' as const, color: '#113CCF', icon: 'tv' },
    { id: uuid(), name: 'Amazon Prime', type: 'category' as const, color: '#FF9900', icon: 'tv' },
    { id: uuid(), name: 'YouTube', type: 'category' as const, color: '#FF0000', icon: 'tv' },
    { id: uuid(), name: 'Spotify', type: 'category' as const, color: '#1DB954', icon: 'music' },
    { id: uuid(), name: 'Notion', type: 'category' as const, color: '#000000', icon: 'layout' },
    { id: uuid(), name: 'ChatGPT', type: 'category' as const, color: '#10A37F', icon: 'bot' },
    { id: uuid(), name: 'Claude', type: 'category' as const, color: '#D4A574', icon: 'bot' },
    { id: uuid(), name: 'Google Premium', type: 'category' as const, color: '#4285F4', icon: 'search' },
    { id: uuid(), name: 'TradingView', type: 'category' as const, color: '#2962FF', icon: 'bar-chart' },
    { id: uuid(), name: 'VPN/VPS', type: 'category' as const, color: '#6366F1', icon: 'shield' },
    { id: uuid(), name: 'Domini', type: 'category' as const, color: '#64748B', icon: 'globe' },
    { id: uuid(), name: 'Software e abbonamenti', type: 'category' as const, color: '#8B5CF6', icon: 'package' },

    // --- CATEGORY - Business ---
    { id: uuid(), name: 'Commercialista personale', type: 'category' as const, color: '#475569', icon: 'calculator' },
    { id: uuid(), name: 'Commercialista aziendale', type: 'category' as const, color: '#475569', icon: 'calculator' },
    { id: uuid(), name: 'Assicurazioni professionali', type: 'category' as const, color: '#DC2626', icon: 'shield' },
    { id: uuid(), name: 'Collaboratori', type: 'category' as const, color: '#F97316', icon: 'users' },
    { id: uuid(), name: 'Ufficio', type: 'category' as const, color: '#64748B', icon: 'building-2' },
    { id: uuid(), name: 'PEC', type: 'category' as const, color: '#3B82F6', icon: 'mail' },
    { id: uuid(), name: 'Fatturazione elettronica', type: 'category' as const, color: '#14B8A6', icon: 'file-check' },
    { id: uuid(), name: 'Whoop', type: 'category' as const, color: '#000000', icon: 'watch' },

    // --- CATEGORY - Entrate ---
    { id: uuid(), name: 'Coreografia', type: 'category' as const, color: '#22C55E', icon: 'music-2' },
    { id: uuid(), name: 'Insegnamento', type: 'category' as const, color: '#22C55E', icon: 'graduation-cap' },
    { id: uuid(), name: 'Formazione / Speaker', type: 'category' as const, color: '#22C55E', icon: 'mic' },
    { id: uuid(), name: 'Consulenza', type: 'category' as const, color: '#22C55E', icon: 'briefcase' },
    { id: uuid(), name: 'Corsi VS / Opzionetika', type: 'category' as const, color: '#22C55E', icon: 'presentation' },
    { id: uuid(), name: 'Earnings (trading)', type: 'category' as const, color: '#22C55E', icon: 'trending-up' },
  ]

  await db.insert(schema.tags).values(tagsData)
  console.log(`   ${tagsData.length} tag creati`)

  // ============================================================
  // CONTROPARTI frequenti
  // ============================================================
  console.log('4. Creazione controparti...')

  const counterpartiesData = [
    // Servizi
    { id: uuid(), name: 'Netflix', type: 'service' as const, defaultCategory: 'Netflix' },
    { id: uuid(), name: 'Spotify', type: 'service' as const, defaultCategory: 'Spotify' },
    { id: uuid(), name: 'Amazon', type: 'service' as const, defaultCategory: 'Amazon Prime' },
    { id: uuid(), name: 'Google', type: 'service' as const, defaultCategory: 'Google Premium' },
    { id: uuid(), name: 'OpenAI', type: 'service' as const, defaultCategory: 'ChatGPT' },
    { id: uuid(), name: 'Anthropic', type: 'service' as const, defaultCategory: 'Claude' },
    { id: uuid(), name: 'TradingView', type: 'service' as const, defaultCategory: 'TradingView' },
    // Enti
    { id: uuid(), name: 'Agenzia delle Entrate', type: 'government' as const, defaultCategory: 'F24 - IVA' },
    { id: uuid(), name: 'Comune di Milano', type: 'government' as const, defaultCategory: 'TARI' },
    // Persone/business
    { id: uuid(), name: 'Proprietario casa', type: 'person' as const, defaultCategory: 'Affitto' },
    { id: uuid(), name: 'Monia (baby sitter)', type: 'person' as const, defaultCategory: 'Baby Sitter' },
    { id: uuid(), name: 'Rosy (baby sitter)', type: 'person' as const, defaultCategory: 'Baby Sitter' },
    // Aziende partner
    { id: uuid(), name: 'Scacco Matto SRLS (Mirko)', type: 'company' as const },
    { id: uuid(), name: 'Shuffle SSRL', type: 'company' as const },
    // Supermercati
    { id: uuid(), name: 'Esselunga', type: 'store' as const, defaultCategory: 'Spesa alimentare' },
    { id: uuid(), name: 'Carrefour', type: 'store' as const, defaultCategory: 'Spesa alimentare' },
    // Utilities
    { id: uuid(), name: 'Enel', type: 'company' as const, defaultCategory: 'Bollette' },
    { id: uuid(), name: 'A2A', type: 'company' as const, defaultCategory: 'Bollette' },
    { id: uuid(), name: 'Telepass', type: 'company' as const, defaultCategory: 'Telepass' },
  ]

  await db.insert(schema.counterparties).values(counterpartiesData)
  console.log(`   ${counterpartiesData.length} controparti creati`)

  // ============================================================
  // SUMMARY
  // ============================================================
  console.log('\n====================================')
  console.log('SEED COMPLETATO')
  console.log('====================================')
  console.log(`Soggetti:     ${subjectsData.length}`)
  console.log(`Contenitori:  ${containersData.length}`)
  console.log(`Tag:          ${tagsData.length}`)
  console.log(`Controparti:  ${counterpartiesData.length}`)
  console.log('====================================\n')
}

seed().catch((err) => {
  console.error('Errore durante il seed:', err)
  process.exit(1)
})
